[log]
log_path="./logs/gobog.log" #log file name
level=7                     #log level
maxlines=0                  #max lines per file
maxsize=0                   #max size per file
daily=true                  #daily rotate
maxdays=10                  #how many days saved log file
color=true                  #color
perm="0755"                 #permission

[http]
cert="${YOUR_CERT_PATH}/1_sbrave.cn_bundle.crt"
key="${YOUR_CERT_PATH}/2_sbrave.cn.key"
# listen 80 address needs root permission
addr=":80"
addrs=":443"

[blog]
domain="https://sbrave.cn"
title="smart的个人博客"
subtitle="代码分享专栏"
description="阅读·实践·分享"
--description="Stay hungry,stay foolish."
author="smart"
theme="themes/simple"
source="${YOUR_SOURCE_PATH}"
